apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-qajr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-qajr
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-qajr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-qajr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-qajr
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mgle-tenant/rhtap-demo-app/hacbs-test-project-qajr@sha256:5f1d927c12e23e83f82720d38d2e9a31bdf8855dd52a78cbecfc96f9a81007e2
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
